export const countries: string[] = [
  'Åland Islands',
  'Afghanistan',
  'Akrotiri',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Ashmore and Cartier Islands',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Bassas Da India',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Clipperton Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Cook Islands',
  'Coral Sea Islands',
  'Costa Rica',
  'Cote D’Ivoire',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Dhekelia',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Europa Island',
  'Falkland Islands (Islas Malvinas)',
  'Faroe Islands',
  'Federated States of Micronesia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern and Antarctic Lands',
  'Gabon',
  'Gaza Strip',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Glorioso Islands',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Jan Mayen',
  'Japan',
  'Jersey',
  'Jordan',
  'Juan De Nova Island',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Navassa Island',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paracel Islands',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint BarthÃ©lemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Korea',
  'South Sudan',
  'Spain',
  'Spratly Islands',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'The Bahamas',
  'The Gambia',
  'Timor-leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tromelin Island',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands',
  'Wake Island',
  'Wallis and Futuna',
  'West Bank',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]
export const countryCodes: { prefix: string; code: string }[] = [
  { prefix: 'AX', code: '358' },
  { prefix: 'AF', code: '93' },
  { prefix: 'AL', code: '355' },
  { prefix: 'DZ', code: '213' },
  { prefix: 'AS', code: '1684' },
  { prefix: 'AD', code: '376' },
  { prefix: 'AO', code: '244' },
  { prefix: 'AI', code: '1264' },
  { prefix: 'AQ', code: '672' },
  { prefix: 'AG', code: '1268' },
  { prefix: 'AR', code: '54' },
  { prefix: 'AM', code: '374' },
  { prefix: 'AW', code: '297' },
  { prefix: 'AU', code: '61' },
  { prefix: 'AT', code: '43' },
  { prefix: 'AZ', code: '994' },
  { prefix: 'BS', code: '1242' },
  { prefix: 'BH', code: '973' },
  { prefix: 'BD', code: '880' },
  { prefix: 'BB', code: '1246' },
  { prefix: 'BY', code: '375' },
  { prefix: 'BE', code: '32' },
  { prefix: 'BZ', code: '501' },
  { prefix: 'BJ', code: '229' },
  { prefix: 'BM', code: '1441' },
  { prefix: 'BT', code: '975' },
  { prefix: 'BO', code: '591' },
  { prefix: 'BA', code: '387' },
  { prefix: 'BW', code: '267' },
  { prefix: 'BR', code: '55' },
  { prefix: 'IO', code: '246' },
  { prefix: 'VG', code: '1284' },
  { prefix: 'BN', code: '673' },
  { prefix: 'BG', code: '359' },
  { prefix: 'BF', code: '226' },
  { prefix: 'MM', code: '95' },
  { prefix: 'BI', code: '257' },
  { prefix: 'KH', code: '855' },
  { prefix: 'CM', code: '237' },
  { prefix: 'CV', code: '238' },
  { prefix: 'BQ', code: '599' },
  { prefix: 'KY', code: '1345' },
  { prefix: 'CF', code: '236' },
  { prefix: 'TD', code: '235' },
  { prefix: 'CL', code: '56' },
  { prefix: 'CN', code: '86' },
  { prefix: 'CX', code: '61' },
  { prefix: 'CC', code: '61' },
  { prefix: 'CO', code: '57' },
  { prefix: 'KM', code: '269' },
  { prefix: 'CK', code: '682' },
  { prefix: 'CR', code: '506' },
  { prefix: 'CI', code: '225' },
  { prefix: 'HR', code: '385' },
  { prefix: 'CU', code: '53' },
  { prefix: 'CW', code: '599' },
  { prefix: 'CY', code: '357' },
  { prefix: 'CZ', code: '420' },
  { prefix: 'CD', code: '243' },
  { prefix: 'DK', code: '45' },
  { prefix: 'DJ', code: '253' },
  { prefix: 'DM', code: '1767' },
  { prefix: 'DO', code: '1809' },
  { prefix: 'EC', code: '593' },
  { prefix: 'EG', code: '20' },
  { prefix: 'SV', code: '503' },
  { prefix: 'GQ', code: '240' },
  { prefix: 'ER', code: '291' },
  { prefix: 'EE', code: '372' },
  { prefix: 'ET', code: '251' },
  { prefix: 'FK', code: '500' },
  { prefix: 'FO', code: '298' },
  { prefix: 'FJ', code: '679' },
  { prefix: 'FI', code: '358' },
  { prefix: 'FR', code: '33' },
  { prefix: 'GF', code: '594' },
  { prefix: 'PF', code: '689' },
  { prefix: 'GA', code: '241' },
  { prefix: 'GM', code: '220' },
  { prefix: 'GE', code: '995' },
  { prefix: 'DE', code: '49' },
  { prefix: 'GH', code: '233' },
  { prefix: 'GI', code: '350' },
  { prefix: 'GR', code: '30' },
  { prefix: 'GL', code: '299' },
  { prefix: 'GD', code: '1473' },
  { prefix: 'GP', code: '590' },
  { prefix: 'GU', code: '1671' },
  { prefix: 'GT', code: '502' },
  { prefix: 'GG', code: '44' },
  { prefix: 'GN', code: '224' },
  { prefix: 'GW', code: '245' },
  { prefix: 'GY', code: '592' },
  { prefix: 'HT', code: '509' },
  { prefix: 'HN', code: '504' },
  { prefix: 'HK', code: '852' },
  { prefix: 'HU', code: '36' },
  { prefix: 'IS', code: '354' },
  { prefix: 'IN', code: '91' },
  { prefix: 'ID', code: '62' },
  { prefix: 'IR', code: '98' },
  { prefix: 'IQ', code: '964' },
  { prefix: 'IE', code: '353' },
  { prefix: 'IM', code: '44' },
  { prefix: 'IL', code: '972' },
  { prefix: 'IT', code: '39' },
  { prefix: 'JM', code: '1876' },
  { prefix: 'JP', code: '81' },
  { prefix: 'JE', code: '44' },
  { prefix: 'JO', code: '962' },
  { prefix: 'KE', code: '254' },
  { prefix: 'KI', code: '686' },
  { prefix: 'XK', code: '383' },
  { prefix: 'KW', code: '965' },
  { prefix: 'KG', code: '996' },
  { prefix: 'LA', code: '856' },
  { prefix: 'LV', code: '371' },
  { prefix: 'LB', code: '961' },
  { prefix: 'LS', code: '266' },
  { prefix: 'LR', code: '231' },
  { prefix: 'LY', code: '218' },
  { prefix: 'LI', code: '423' },
  { prefix: 'LT', code: '370' },
  { prefix: 'LU', code: '352' },
  { prefix: 'MO', code: '853' },
  { prefix: 'MK', code: '389' },
  { prefix: 'MG', code: '261' },
  { prefix: 'MW', code: '265' },
  { prefix: 'MY', code: '60' },
  { prefix: 'MV', code: '960' },
  { prefix: 'ML', code: '223' },
  { prefix: 'MT', code: '356' },
  { prefix: 'MH', code: '692' },
  { prefix: 'MQ', code: '596' },
  { prefix: 'MR', code: '222' },
  { prefix: 'MU', code: '230' },
  { prefix: 'YT', code: '262' },
  { prefix: 'MX', code: '52' },
  { prefix: 'MD', code: '373' },
  { prefix: 'MC', code: '377' },
  { prefix: 'MN', code: '976' },
  { prefix: 'ME', code: '382' },
  { prefix: 'MS', code: '1664' },
  { prefix: 'MA', code: '212' },
  { prefix: 'MZ', code: '258' },
  { prefix: 'NA', code: '264' },
  { prefix: 'NR', code: '674' },
  { prefix: 'NP', code: '977' },
  { prefix: 'NL', code: '31' },
  { prefix: 'NC', code: '687' },
  { prefix: 'NZ', code: '64' },
  { prefix: 'NI', code: '505' },
  { prefix: 'NE', code: '227' },
  { prefix: 'NG', code: '234' },
  { prefix: 'NU', code: '683' },
  { prefix: 'NF', code: '672' },
  { prefix: 'KP', code: '850' },
  { prefix: 'MP', code: '1670' },
  { prefix: 'NO', code: '47' },
  { prefix: 'OM', code: '968' },
  { prefix: 'PK', code: '92' },
  { prefix: 'PW', code: '680' },
  { prefix: 'PS', code: '970' },
  { prefix: 'PA', code: '507' },
  { prefix: 'PG', code: '675' },
  { prefix: 'PY', code: '595' },
  { prefix: 'PE', code: '51' },
  { prefix: 'PH', code: '63' },
  { prefix: 'PN', code: '64' },
  { prefix: 'PL', code: '48' },
  { prefix: 'PT', code: '351' },
  { prefix: 'PR', code: '1787' },
  { prefix: 'QA', code: '974' },
  { prefix: 'CG', code: '242' },
  { prefix: 'RE', code: '262' },
  { prefix: 'RO', code: '40' },
  { prefix: 'RU', code: '7' },
  { prefix: 'RW', code: '250' },
  { prefix: 'BL', code: '590' },
  { prefix: 'SH', code: '290' },
  { prefix: 'KN', code: '1869' },
  { prefix: 'LC', code: '1758' },
  { prefix: 'MF', code: '590' },
  { prefix: 'PM', code: '508' },
  { prefix: 'VC', code: '1784' },
  { prefix: 'WS', code: '685' },
  { prefix: 'SM', code: '378' },
  { prefix: 'ST', code: '239' },
  { prefix: 'SA', code: '966' },
  { prefix: 'SN', code: '221' },
  { prefix: 'RS', code: '381' },
  { prefix: 'SC', code: '248' },
  { prefix: 'SL', code: '232' },
  { prefix: 'SG', code: '65' },
  { prefix: 'SX', code: '1721' },
  { prefix: 'SK', code: '421' },
  { prefix: 'SI', code: '386' },
  { prefix: 'SB', code: '677' },
  { prefix: 'SO', code: '252' },
  { prefix: 'ZA', code: '27' },
  { prefix: 'KR', code: '82' },
  { prefix: 'SS', code: '211' },
  { prefix: 'ES', code: '34' },
  { prefix: 'LK', code: '94' },
  { prefix: 'SD', code: '249' },
  { prefix: 'SR', code: '597' },
  { prefix: 'SJ', code: '47' },
  { prefix: 'SZ', code: '268' },
  { prefix: 'SE', code: '46' },
  { prefix: 'CH', code: '41' },
  { prefix: 'SY', code: '963' },
  { prefix: 'TW', code: '886' },
  { prefix: 'TJ', code: '992' },
  { prefix: 'TZ', code: '255' },
  { prefix: 'TH', code: '66' },
  { prefix: 'GM', code: '220' },
  { prefix: 'TL', code: '670' },
  { prefix: 'TG', code: '228' },
  { prefix: 'TK', code: '690' },
  { prefix: 'TO', code: '676' },
  { prefix: 'TT', code: '1868' },
  { prefix: 'TN', code: '216' },
  { prefix: 'TR', code: '90' },
  { prefix: 'TM', code: '993' },
  { prefix: 'TC', code: '1649' },
  { prefix: 'TV', code: '688' },
  { prefix: 'UG', code: '256' },
  { prefix: 'UA', code: '380' },
  { prefix: 'AE', code: '971' },
  { prefix: 'GB', code: '44' },
  { prefix: 'US', code: '1' },
  { prefix: 'UY', code: '598' },
  { prefix: 'UZ', code: '998' },
  { prefix: 'VU', code: '678' },
  { prefix: 'VE', code: '58' },
  { prefix: 'VN', code: '84' },
  { prefix: 'VI', code: '1340' },
  { prefix: 'WF', code: '681' },
  { prefix: 'EH', code: '212' },
  { prefix: 'YE', code: '967' },
  { prefix: 'ZM', code: '260' },
  { prefix: 'ZW', code: '263' }
]
